<#
# ══════════════════════════════════════════════════════════════════════════
#  seren-observatory-setup.ps1  -  one-shot SerenObservatory installer (Windows)
#
#  Refactored to dot-source seren-install-lib.ps1 (shared installer library).
#  Identity lines + config are the only unique parts.
#
#  USAGE (same flags as before)
#    powershell -ExecutionPolicy Bypass -File .\seren-observatory-setup.ps1
#    powershell -ExecutionPolicy Bypass -File .\seren-observatory-setup.ps1 -Service
#    powershell -ExecutionPolicy Bypass -File .\seren-observatory-setup.ps1 -Wheel .\seren_observatory-0.1.0-py3-none-any.whl
#    powershell -ExecutionPolicy Bypass -File .\seren-observatory-setup.ps1 -NoUpdates  # turn update checking off
# ══════════════════════════════════════════════════════════════════════════
#>
[CmdletBinding()]
param(
  [int]    $Port      = 7777,
  [string] $ObsHost   = "0.0.0.0",
  [string] $Wheel     = "",
  [string] $Ref       = "",
  [string] $Repo      = "ChadRoesler/SerenObservatory",
  [switch] $Service,
  [switch] $Updates,
  [switch] $NoUpdates,
  [string] $Instance  = "",
  [string] $VenvDir   = "",
  [switch] $Describe,   # print service metadata as JSON and exit (no side effects)
  [switch] $Json        # stream JSON Lines events on stdout; humans go to stderr
)

$ErrorActionPreference = "Stop"
$ScriptDir = $PSScriptRoot

# -- locate a file by walking UP the tree (reorg-robust; injected by fixup) ---
function Find-Upward {
    param([Parameter(Mandatory)] [string] $Rel, [string] $Start = $PSScriptRoot)
    $dir = $Start
    while ($dir) {
        $candidate = Join-Path $dir $Rel
        if (Test-Path $candidate) { return (Resolve-Path $candidate).Path }
        $parent = Split-Path $dir -Parent
        if ($parent -eq $dir) { break }
        $dir = $parent
    }
    return $null
}

# -- source the shared installer library ---------------------------------------
$lib = Find-Upward "services\lib\seren-install-lib.ps1"
if (-not $lib) { Write-Host "ERROR: seren-install-lib.ps1 not found. Keep services/lib/ with shared scripts." -ForegroundColor Red; exit 1 }
. $lib


# -- Starwright contracts -----------------------------------------------------
# -Describe answers with ZERO side effects, so it runs before anything else.
if ($Describe) {
    $describeArgs = @{
        ScriptPath  = $PSCommandPath
        Name        = 'seren-observatory'
        Display     = 'Seren Observatory'
        Description = 'The insight into the node'
        Group       = 'core'
        Package     = 'seren-observatory'
        Accent      = '#f59056'
        DefaultHost = $ObsHost
        DefaultPort = $Port
    }
    Get-SerenDescribe @describeArgs
    exit 0
}
if ($Json) { Enable-SerenJson }
if (-not $VenvDir) { $VenvDir = "$env:USERPROFILE\seren-venvs\observatory" }
$VenvDir = "$VenvDir$Instance"
$AppDir  = "$env:USERPROFILE\seren-observatory$Instance"
$CfgPath = "$AppDir\seren-observatory.yaml"
$global:Instance = $Instance
if ($Instance -and $Port -eq 7777) {
  Warn "Instance '$Instance' uses default port 7777 — may collide."
}

Write-Host "==========================================" -ForegroundColor Green
Write-Host "  SerenObservatory setup (Windows)" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green

# -- 1. find Python ------------------------------------------------------------
$pyInfo = Find-Python
$global:pyInfo = $pyInfo

# -- 2. resolve wheel (observatory uses -Repo by default, not PyPI) ------------
$wr = Resolve-Wheel -Wheel $Wheel -Ref $Ref -Repo $Repo -Package "seren-observatory"

# -- 3. venv + install (no extras) ---------------------------------------------
$vpy = Create-Venv -VenvDir $VenvDir -PyExe $pyInfo.Exe -PyArgs $pyInfo.Args
$Mcp = $false; $Corp = $false  # observatory has no extras
if ($Updates) { Write-Host "  ! -Updates is unnecessary: update checking ships on by default" -ForegroundColor Yellow }
$extras = Get-Extras-Suffix
Install-Package -Vpy $vpy -WheelSrc $wr.Src -Extras $extras -Label ""
if ($wr.Cleanup) { Remove-Item -Force $wr.Src -ErrorAction SilentlyContinue }

# -- 4. sanity check -----------------------------------------------------------
Sanity-Check -Vpy $vpy -Module "seren_observatory" -AssetRelPath "viewer/ui/body.html" -AssetLabel "viewer"

# -- 5. config ------------------------------------------------------------------
Step "Writing config at $CfgPath"
New-Item -ItemType Directory -Force -Path $AppDir | Out-Null
if (Test-Path $CfgPath) {
  $bak = "$CfgPath.bak.$([int][double]::Parse((Get-Date -UFormat %s)))"
  Copy-Item $CfgPath $bak; Warn "Backed up to $(Split-Path $bak -Leaf)"
}
@"
# SerenObservatory config - generated by seren-observatory-setup.ps1
# The bearer TOKEN is NOT here - it's a safety interlock in
# ~/.seren/secrets.json (run seren-secrets). See the repo's yaml sample.
server:
  host: $ObsHost
  port: $Port
"@ | Set-Content -Path $CfgPath -Encoding UTF8
Ok "Config written"

if ($NoUpdates) {
    # Update checking is ON by default across the Seren family: it asks the
    # package index whether a newer release exists and reports it on the info
    # route. It NEVER upgrades anything. -NoUpdates writes the off switch.
    @"

# ── Update checking ───────────────────────────────────────────────────
# Turned OFF at install time by -NoUpdates. Flip to true to re-enable, or set
# SEREN_<SERVICE>_UPDATES_ENABLED=true in the service environment.
updates:
  enabled: false
"@ | Add-Content -Path $CfgPath -Encoding UTF8
    Ok "Update checking disabled in config"
}

# -- 5b. launcher ---------------------------------------------------------------
$launcher = Write-Launcher -AppDir $AppDir -ServiceName "seren-observatory" -Vpy $vpy -Module "seren_observatory" -CfgPath $CfgPath

# -- 6. optional autostart ------------------------------------------------------
if ($Service) { Setup-Autostart -ScriptDir $ScriptDir -ServiceName "seren-observatory" -AppDir $AppDir -Token "" -VenvDir $VenvDir }

# -- done -----------------------------------------------------------------------
$connectHost = if ($ObsHost -eq "0.0.0.0") { "127.0.0.1" } else { $ObsHost }
Write-Host ""
Write-Host "==========================================" -ForegroundColor Green
Write-Host "  SerenObservatory is set up +" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green
if (-not $Service) {
  Write-Host "  Start it:        $launcher" -ForegroundColor Blue
}
Write-Host "  Ping:            http://${connectHost}:$Port/api/v1/system/ping" -ForegroundColor Blue
Write-Host ""
Write-Host "  Token is a safety interlock: run seren-secrets to write ~/.seren/secrets.json." -ForegroundColor Yellow
Write-Host "  Until then the observatory fails CLOSED on management endpoints." -ForegroundColor Yellow
Write-Host "Rip it and win. 🌭🔧" -ForegroundColor Green

# -- Starwright contract: structured completion event -------------------------
# Human banner above, machine-readable twin here. No-op without -Json.
$doneArgs = @{
    Service     = 'seren-observatory'
    ConnectHost = $connectHost
    Port        = $Port
    Autostart   = ([bool] $Service)
    Token       = ""
    Mcp         = ([bool] $Mcp)
    Corp        = ([bool] $Corp)
    Vector      = $false
    Venv        = $VenvDir
    Config      = $CfgPath
}
Send-SerenDone @doneArgs
