<#
# ══════════════════════════════════════════════════════════════════════════
#  seren-probe-setup.ps1  -  one-shot SerenProbe installer (Windows)
#
#  Local-only memory (RAG) Evaluation probe. No MCP, no TLS, no bearer token —
#  it's a private infra tool that only binds to 127.0.0.1.
#
#  USAGE
#    powershell -ExecutionPolicy Bypass -File .\seren-probe-setup.ps1
#    powershell -ExecutionPolicy Bypass -File .\seren-probe-setup.ps1 -Service
#    powershell -ExecutionPolicy Bypass -File .\seren-probe-setup.ps1 -Wheel .\seren_probe-0.1.0-py3-none-any.whl
#    powershell -ExecutionPolicy Bypass -File .\seren-probe-setup.ps1 -NoUpdates  # turn update checking off
# ══════════════════════════════════════════════════════════════════════════
#>
[CmdletBinding()]
param(
  [int]    $Port      = 7430,
  [string] $ProbeHost = "127.0.0.1",
  [string] $Wheel     = "",
  [string] $Ref       = "",
  [string] $Repo      = "",
  [switch] $Service,
  [switch] $Mcp,
  [switch] $Corp,
  [switch] $NoUpdates,
  # -- service identity (only meaningful alongside -Service) -------------------
  # Forwarded to the NSSM wrapper. The password is NOT a parameter - it rides
  # in $env:SEREN_SERVICE_PASSWORD, because on Windows a command line is
  # readable by any other process.
  [string] $ServiceUser = "",
  [switch] $LocalSystem,
  [string] $Instance  = "",
  [string] $VenvDir   = "",
  [switch] $Describe,
  [switch] $Json
)

$ErrorActionPreference = "Stop"
$ScriptDir = $PSScriptRoot

# -- locate a file by walking UP the tree (reorg-robust) -----------------------
function Find-Upward {
    param([Parameter(Mandatory)] [string] $Rel, [string] $Start = $PSScriptRoot)
    $dir = $Start
    while ($dir) {
        $candidate = Join-Path $dir $Rel
        if (Test-Path $candidate) { return (Resolve-Path $candidate).Path }
        $parent = Split-Path $dir -Parent
        if ($parent -eq $dir) { break }
        $dir = $parent
    }
    return $null
}

# -- source the shared installer library ---------------------------------------
$lib = Find-Upward "services\lib\seren-install-lib.ps1"
if (-not $lib) { Write-Host "ERROR: seren-install-lib.ps1 not found. Keep services/lib/ with shared scripts." -ForegroundColor Red; exit 1 }
. $lib

# -- Starwright contracts -----------------------------------------------------
if ($Describe) {
    $describeArgs = @{
        ScriptPath  = $PSCommandPath
        Name        = 'seren-probe'
        Display     = 'Seren Probe'
        Description = 'Memory (RAG) Evaluation'
        Group       = 'auxiliary'
        Package     = 'seren-probe'
        Accent      = '#7fd88f'
        DefaultHost = $ProbeHost
        DefaultPort = $Port
    }
    Get-SerenDescribe @describeArgs
    exit 0
}
if ($Json) { Enable-SerenJson }
if (-not $VenvDir) { $VenvDir = "$env:USERPROFILE\seren-venvs\probe" }
$VenvDir = "$VenvDir$Instance"
$AppDir  = "$env:USERPROFILE\seren-probe$Instance"
$CfgPath = "$AppDir\seren-probe.yaml"
$global:Instance = $Instance
if ($Instance -and $Port -eq 7430) {
  Warn "Instance '$Instance' uses default port 7430 — may collide."
}

Write-Host "==========================================" -ForegroundColor Green
Write-Host "  SerenProbe setup (Windows)" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green

# -- 1. find Python (3.10-3.12) -------------------------------------------------
$pyInfo = Find-Python
$global:pyInfo = $pyInfo

if ($Ref -and -not $Repo) { $Repo = "ChadRoesler/SerenProbe" }

# -- 2. resolve wheel ----------------------------------------------------------
$wr = Resolve-Wheel -Wheel $Wheel -Ref $Ref -Repo $Repo -Package "seren-probe"

# -- 3. venv + install ---------------------------------------------------------
$vpy = Create-Venv -VenvDir $VenvDir -PyExe $pyInfo.Exe -PyArgs $pyInfo.Args
$extras = Get-Extras-Suffix -Mcp:$Mcp -Corp:$Corp
Install-Package -Vpy $vpy -WheelSrc $wr.Src -Extras $extras -Label ""
if ($wr.Cleanup) { Remove-Item -Force $wr.Src -ErrorAction SilentlyContinue }

# -- 4. sanity check (import + viewer/probe.html) -----------------------------
Sanity-Check -Vpy $vpy -Module "seren_probe" -AssetRelPath "viewer/probe.html" -AssetLabel "viewer"

# -- 5. config --------------------------------------------------------------
Step "Writing config at $CfgPath"
New-Item -ItemType Directory -Force -Path $AppDir | Out-Null
if (Test-Path $CfgPath) {
  $bak = "$CfgPath.bak.$([int][double]::Parse((Get-Date -UFormat %s)))"
  Copy-Item $CfgPath $bak
  Warn "Existing config backed up to $(Split-Path $bak -Leaf)"
}
@"
# SerenProbe config - generated by seren-probe-setup.ps1
# Full reference: see seren-probe.yaml.sample in the repo.
server:
  host: $ProbeHost
  port: $Port

storage:
  db_path: ~/.seren-probe$Instance/probe.db
"@ | Write-SerenTextFile -Path $CfgPath
Ok "Config written"

if ($NoUpdates) {
    # Update checking is ON by default across the Seren family: it asks the
    # package index whether a newer release exists and reports it on the info
    # route. It NEVER upgrades anything. -NoUpdates writes the off switch.
    @"

# ── Update checking ───────────────────────────────────────────────────
# Turned OFF at install time by -NoUpdates. Flip to true to re-enable, or set
# SEREN_<SERVICE>_UPDATES_ENABLED=true in the service environment.
updates:
  enabled: false
"@ | Add-SerenTextFile -Path $CfgPath
    Ok "Update checking disabled in config"
}

# -- 5b. launcher -----------------------------------------------------------
$launcher = Write-Launcher -AppDir $AppDir -ServiceName "seren-probe" -Vpy $vpy -Module "seren_probe" -CfgPath $CfgPath

# -- 6. optional autostart ----------------------------------------------------
if ($Service) { Setup-Autostart -ScriptDir $ScriptDir -ServiceName "seren-probe" -AppDir $AppDir -Token "" -VenvDir $VenvDir -ServiceUser $ServiceUser -LocalSystem:$LocalSystem }

# -- done -------------------------------------------------------------------
$connectHost = if ($ProbeHost -eq "0.0.0.0") { "127.0.0.1" } else { $ProbeHost }
Write-Host ""
Write-Host "==========================================" -ForegroundColor Green
Write-Host "  SerenProbe is set up ✓" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green
if (-not $Service) {
  Write-Host "  Start it:        $launcher" -ForegroundColor Blue
}
Write-Host "  Dashboard:        http://${connectHost}:$Port/probe" -ForegroundColor Blue
Write-Host "  Health:           http://${connectHost}:$Port/health" -ForegroundColor Blue
Write-Host "Rip it and win. 🌭🔧" -ForegroundColor Green

# -- Starwright contract: structured completion event -------------------------
$doneArgs = @{
    Service     = 'seren-probe'
    ConnectHost = $connectHost
    Port        = $Port
    Autostart   = ([bool] $Service)
    Token       = ""
    Mcp         = $false
    Corp        = $false
    Vector      = $false
    Venv        = $VenvDir
    Config      = $CfgPath
}
Send-SerenDone @doneArgs
