#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════
#  A reinstall keeps what the card does not write.
#
#  Seen live 25 Sept 2026: the hippocampus reinstalled, its config was
#  rewritten from the card's template, and the model.lifecycle block the
#  operator had added was gone. seren-keep-config.py (run by write_launcher,
#  before the service starts) puts back what the backup had and the new
#  file lacks - and only that.
#
#  Run:  bash services/tests/test-keep-config.sh   (Git Bash is fine)
# ══════════════════════════════════════════════════════════════
set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PASS=0; FAILS=0
ok_()  { PASS=$((PASS+1)); echo "  ok   $1"; }
bad()  { FAILS=$((FAILS+1)); echo "  FAIL $1"; }
has()  { if grep -qF -- "$2" "$3"; then ok_ "$1"; else bad "$1"; fi; }
hasnt(){ if grep -qF -- "$2" "$3"; then bad "$1"; else ok_ "$1"; fi; }

PY=""
for c in python python3; do
  command -v "$c" >/dev/null 2>&1 || continue
  "$c" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 8) else 1)' >/dev/null 2>&1 && { PY="$c"; break; }
done
[[ -n "$PY" ]] || { echo "no python found"; exit 1; }
T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
win() { cygpath -m "$1" 2>/dev/null || echo "$1"; }
KEEP="$(win "$HERE/services/lib/seren-keep-config.py")"
CFG="$T/seren-hippocampus.yaml"

# what the operator had
cat > "$CFG.bak.1" <<'YAML'
# SerenHippocampus config - generated by seren-hippocampus-setup.sh
server:
  host: 127.0.0.1
  port: 7269
  bearer_token: "old-token"

memory:
  url: http://127.0.0.1:7267

model:
  url: "http://localhost:7200/v1"
  lifecycle:
    manage: true
    start: '"C:\llama\llama-server.exe" -m C:\m.gguf --port 7200'   # by hand
    keep_warm_seconds: 300

sleep:
  mode: thread
  at: "03:30"

notify:
  webhook_url: http://lodestar:6361/hooks/hippocampus
YAML
# what the card writes on the reinstall
cat > "$CFG" <<'YAML'
# SerenHippocampus config - generated by seren-hippocampus-setup.sh
server:
  host: 127.0.0.1
  port: 7270
  bearer_token: "old-token"

memory:
  url: http://127.0.0.1:7267

model:
  url: "http://localhost:7201/v1"

sleep:
  mode: thread
  state_path: ~/.seren-hippocampus/state.json
YAML

echo "== the reinstall case"
out="$("$PY" "$KEEP" "$(win "$CFG")")"
if grep -q "model.lifecycle" <<<"$out" && grep -q "notify" <<<"$out" && grep -q "sleep.at" <<<"$out"; then ok_ "it says what it kept: $out"; else bad "it says what it kept: $out"; fi
has   "the lifecycle block is back"                       "  lifecycle:" "$CFG"
has   "...with its nested keys and its comment"           "--port 7200'   # by hand" "$CFG"
has   "a hand-set key under a written block is back"      '  at: "03:30"' "$CFG"
has   "a whole block the card never writes is back"       "webhook_url: http://lodestar:6361/hooks/hippocampus" "$CFG"
has   "what the card wrote wins (port)"                   "  port: 7270" "$CFG"
hasnt "...and the old port is not added back"             "port: 7269" "$CFG"
has   "what the card wrote wins (model url)"              'url: "http://localhost:7201/v1"' "$CFG"
has   "the card's new keys stay"                          "state_path: ~/.seren-hippocampus/state.json" "$CFG"
"$PY" - "$(win "$CFG")" <<'PYC' && ok_ "lifecycle sits under model, not at the end" || bad "lifecycle sits under model, not at the end"
import sys, re
t = open(sys.argv[1], encoding="utf-8").read()
m = t.index("model:"); l = t.index("  lifecycle:"); s = t.index("\nsleep:")
sys.exit(0 if m < l < s else 1)
PYC
cp "$CFG" "$T/after-first"
"$PY" "$KEEP" "$(win "$CFG")" >/dev/null
if cmp -s "$CFG" "$T/after-first"; then ok_ "running it twice changes nothing"; else bad "running it twice changes nothing"; fi

echo "== a stale backup and a fresh install"
CFG2="$T/seren-loci.yaml"
printf 'server:\n  port: 7422\n' > "$CFG2"
printf 'server:\n  port: 7422\nold_block:\n  x: 1\n' > "$CFG2.bak.2"
touch -d "3 hours ago" "$CFG2.bak.2" 2>/dev/null || "$PY" -c "import os,sys,time; t=time.time()-3*3600; os.utime(sys.argv[1],(t,t))" "$(win "$CFG2.bak.2")"
"$PY" "$KEEP" "$(win "$CFG2")" >/dev/null
hasnt "a backup older than an hour is ignored"           "old_block" "$CFG2"
CFG3="$T/seren-margin.yaml"
printf 'server:\n  port: 7421\n' > "$CFG3"
"$PY" "$KEEP" "$(win "$CFG3")" >/dev/null
if [[ "$(cat "$CFG3")" == $'server:\n  port: 7421' ]]; then ok_ "no backup: the file is untouched"; else bad "no backup: the file is untouched"; fi

echo
echo "  $PASS passed, $FAILS failed"
exit $FAILS
